---
- name: Setup security in the machine Linux
  hosts: all
  become: true
  gather_facts: true
  roles:
#    - {role: chrony, tags: Chrony}
#    - {role: commons, tags: Commons}
#    - {role: security_hardening, tags: Security}
    - {role: docker, tags: Docker}
