---
- name: Install chrony package
  description: Install chrony package
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true

- name: Configure the timezone to America/Sao_Paulo
  ansible.builtin.command: timedatectl set-timezone America/Sao_Paulo

- name: Enable and start chrony service
  ansible.builtin.systemd:
    name: chrony
    enabled: true
    state: started

- name: Sync the system clock with the chrony server
  ansible.builtin.command: chronyc tracking
  register: chrony_status
  failed_when: "'Leap status     : Normal' not in chrony_status.stdout"
  notify: Restart chrony service

- name: Display current date and time
  ansible.builtin.command: date
  register: current_date_time

- name: Display chrony status
  ansible.builtin.debug:
    msg: "{{ current_date_time.stdout }}"
